### ISSUE TITLE
Points inadvertently left out of coloring schemes

### ISSUE THREAD

**Issue by jembrown** [TreeScaper/CloudforestVisualization#12]
When entering tree indices manually to color points in an NLDR plot, I found that the last point in the first range was inadvertently left out. In other words, the first range seemed to be exclusive of the last index.

For an NLDR plot with 100 points, I entered:

[1-65:blue];[66:red];[67-100:blue]

and point 65 remained black.

**Comment by reid-wagner** [comment]
Hi @jembrown, thanks for the report. This is fixed in the latest version.
