### ISSUE TITLE
CD Visualizations not working

### ISSUE THREAD

**Issue by btoup15** [TreeScaper/CloudforestVisualization#9]
It seems like the visualizations for CD aren't working right now, when you go to create a visualization and select CD results or plateaus, the plot area stays blank unless you select other inputs like NLDR. I think previously we were able to view CD results by creating a visualization for the NLDR output file that included CD results, and now that that combined output was removed there doesn't seem to be a way to normally view them.

**Comment by tmcgowan** [comment]
This is now fixed and the latest docker image contains the fix. The beta web site is now using the fixed docker image.
